### ISSUE TITLE
Article number wraps when Dynamic Type too large

### ISSUE THREAD

**Issue by cheeaun** [cheeaun/hackerweb-ios#12]
From @duncansmart

> Small bug: if text size/Dynamic Type is set to larger than default, the article numbers wrap:

![image1](https://cloud.githubusercontent.com/assets/2296/21797191/84502396-d748-11e6-8cc6-975ab9e057b0.PNG)

**Comment by caudaganesh** [comment]
@cheeaun hello sir, can i take this issue?
